services:
- type: web
  name: bikerr
  runtime: node
  plan: free
  envVars:
  - key: postgresql://bikerr:vrStKV0wuyKwjAkmySWnrnrdo4EJugNZ@dpg-d18pbn2dbo4c73ck2ev0-a/bikerr
    fromDatabase:
      name: bikerr
      property: connectionString
  region: Singapore # optional: customize this region
  buildCommand: npm install --production=false
  startCommand: npm run start
  preDeployCommand: npx prisma migrate deploy

databases:
- name: express-with-prisma-orm-db
  databaseName: express_prisma_db
  user: bikerr
  plan: free
  region: Singapore
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"

version: "1"